### ISSUE TITLE
Blake

### ISSUE THREAD

**Issue by iandoug** [adurandom/CryptAda#4]
Hi
Any plans to add anything from the Blake family?
thanks.

**Comment by adurandom** [comment]
BLAKE 1 (224, 256, 384, 512), BLAKE 2s, and BLAKE 2b are already implemented (Branch Cipher_Modes). The source code is at:

https://github.com/adurandom/CryptAda/tree/Cipher_Modes/src/digests

Also unit and time trial tests are available.

BLAKE2 is implemented with some limitations (no parallel, no tree).

**Comment by iandoug** [comment]
Ah, great. Thanks :-)
Didn't think to check the branches before asking.

Cheers, Ian

**Comment by adurandom** [comment]
No prob.
